#!/bin/bash  
sudo yum update -y 
sudo yum install -y httpd 
sudo systemctl start httpd 
sudo systemctl enable httpd 
sudo echo "<h1>Week 5 Project - LUIT Orange Team- Dirie Hersi </h1>" > /var/www/html/index.html
